walker: migrate to elephant menus

diff --git a/dot_local/share/bin/executable_lio-launch-floating-terminal b/dot_local/share/bin/executable_lio-launch-floating-terminal
--- a/dot_local/share/bin/executable_lio-launch-floating-terminal
+++ b/dot_local/share/bin/executable_lio-launch-floating-terminal
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -xeu
 
 # Default to showing the prompt
 show_prompt=true
@@ -19,6 +20,8 @@ inner_cmd+="$cmd;"
 
 if $show_prompt; then
     inner_cmd+="echo 'Done! Press any key to close...'; read -n 1 -s"
+else
+    inner_cmd+="if [ \$? -ne 0 ]; then echo 'Failed! press any key to close...'; read -n 1 -s; fi"
 fi
 
 exec setsid uwsm app -- $TERMINAL_CLEAN --class=System -e bash -c "$inner_cmd"
